version: '3.8'

services:
  go-server:
    build:
      context: ./go-server  # Path to the Go server folder
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb+srv://pkp-admin:param22@cluster0.kftllgo.mongodb.net/blogDB?retryWrites=true&w=majority
    env_file:
      - ./go-server/.env
    networks:
      - blog-network
    depends_on:
      - mongo
    restart: always

  nextjs:
      build:
        context: ./nextwithgo
      ports:
        - "3000:3000"
      environment:
        - NODE_ENV=production
        - NEXT_PUBLIC_API_URL=http://go-server:3001  # Pass API URL
      networks:
        - blog-network
      depends_on:
        - go-server
      restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - blog-network
    restart: always

networks:
  blog-network:
    driver: bridge
    
volumes:
  mongo_data:
