version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Path to the Go server folder
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    networks:
      - blog-network
    depends_on:
      - mongo
    restart: always

  nextjs:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://blogsgo-backend.onrender.com/api  # Direct API URL
    networks:
      - blog-network
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - blog-network
    restart: always

networks:
  blog-network:
    driver: bridge

volumes:
  mongo_data:
