version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Path to the Go server folder
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    networks:
      - blog-network
    depends_on:
      - mongo
    restart: always

  nextjs:
    build:
      context: ./frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=/api  # API route handled by Nginx
    networks:
      - blog-network
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - blog-network
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Use a custom Nginx config
    depends_on:
      - nextjs
      - backend
    networks:
      - blog-network
    restart: always

networks:
  blog-network:
    driver: bridge

volumes:
  mongo_data:
